version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AVA-integration
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
